import { IsString, IsOptional, IsIn, IsBoolean } from 'class-validator';

export class CreateJournalDto {
  @IsString()
  title: string;

  @IsString()
  @IsOptional()
  description?: string;

  @IsString()
  @IsIn(['family', 'friends', 'romantic', 'vacation', 'custom'])
  template_type: string;

  @IsString()
  @IsOptional()
  @IsIn(['daily', 'weekly', 'biweekly', 'monthly'])
  prompt_frequency?: string;

  @IsOptional()
  prompt_day_of_week?: number;

  @IsString()
  @IsOptional()
  prompt_time?: string;

  @IsString()
  @IsOptional()
  timezone?: string;

  @IsString()
  @IsOptional()
  owner_phone?: string;

  @IsBoolean()
  @IsOptional()
  owner_participate?: boolean;

  /**
   * Whether to auto-generate a queue of upcoming prompts from the template
   * defaults at creation time. Defaults to true: the user told us they want
   * prompts to be auto-generated by the app, with the option to override
   * them later from the "Upcoming prompts" UI. Set to false to start with
   * an empty queue (the owner can add custom prompts manually).
   */
  @IsBoolean()
  @IsOptional()
  seed_prompts?: boolean;
}
